# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- features/*

pool: Default

steps:
- powershell: ./.build/build.ps1
  displayName: 'Pack nuget package'
- powershell: Write-Host "Nuget package built $(packageFileName)"
- task: CopyFiles@2
  inputs: 
    sourceFolder: './.packages/$(packageFileName).nupkg'
    contents: '*.nupkg'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'nugetPackage'
    