# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- features/*

jobs:
- job: SetupJob
  pool: Default
  steps:
  - powershell: ./.build/setup.ps1
    workingDirectory: $(build.sourceDirectory)

- job: BuildJob
  pool: Default
  dependsOn: SetupJob
  steps:
  - powershell: ./.build/build.ps1
    displayName: 'Pack nuget package'
  - task: CopyFiles@2
    inputs: 
      sourceFolder: './.packages/'
      contents: '*.nupkg'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      PathToPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'nugetPackage'
