# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- features/*

variables:
  agentImage: "windows-latest"

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(agentImage)
    steps:
    - powershell: ./.build/setup.ps1
      displayName: Prepare directories
    - powershell: ./.build/build.ps1
      displayName: Retrieve package version from GIT
    - task: NugetCommand@2
      displayName: Pack nuget package
      inputs:
        command: pack
        packagesToPack: ./PackageContent/Package.nuspec
        versioningScheme: byEnvVar
        versionEnvVar: packageVersion
    - task: PublishBuildArtifacts@1
      inputs:
        PathToPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'nugetPackage'

- stage: Deploy_Dev
  displayName: Deploy Development
  dependsOn: Build
  jobs: 
  - job: D2AzureArtifacts
    displayName: Deploy nuget package to Azure Artifacts
    pool:
      vmImage: $(agentImage)
    steps:
    - task: NugetCommand@2
      displayName: "Nuget push to Azure Artifacts"
      inputs:
        command: push
        publishVstsFeed: zhusmelbtech

